import { Documento } from '../../features/documentos/models/documento.model';

export const DTO_DOCUMENTOS_EXP1: Documento[] = [
  {
    id: 1,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Demanda_Inicial.pdf',
    tipoDocumento: 'Demanda',
    tipoDocumentoId: 1,
    tamanio: 250880,
    mimeType: 'application/pdf',
    extension: 'pdf',
    categoria: 'pdf',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-04-19T09:00:00',
  },
  {
    id: 2,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Resolucion_Admision.pdf',
    tipoDocumento: 'Auto',
    tipoDocumentoId: 9,
    tamanio: 193536,
    mimeType: 'application/pdf',
    extension: 'pdf',
    categoria: 'pdf',
    usuarioCreacion: 'juez.qa',
    fechaCreacion: '2026-04-20T10:30:00',
  },
  {
    id: 3,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Contestacion_Demanda.pdf',
    tipoDocumento: 'Contestación de demanda',
    tipoDocumentoId: 2,
    tamanio: 319488,
    mimeType: 'application/pdf',
    extension: 'pdf',
    categoria: 'pdf',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-04-25T11:00:00',
  },
  {
    id: 4,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Cedula_Notificacion.pdf',
    tipoDocumento: 'Cédula de notificación',
    tipoDocumentoId: 17,
    tamanio: 100352,
    mimeType: 'application/pdf',
    extension: 'pdf',
    categoria: 'pdf',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-04-26T08:15:00',
  },
  {
    id: 5,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Sentencia_Ordinario.pdf',
    tipoDocumento: 'Sentencia',
    tipoDocumentoId: 11,
    tamanio: 430080,
    mimeType: 'application/pdf',
    extension: 'pdf',
    categoria: 'pdf',
    usuarioCreacion: 'juez.qa',
    fechaCreacion: '2026-05-10T16:00:00',
  },
  {
    id: 6,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Grabacion_Audiencia.mp4',
    tipoDocumento: 'Medios Audiovisuales',
    tipoDocumentoId: 21,
    tamanio: 15485760,
    mimeType: 'video/mp4',
    extension: 'mp4',
    categoria: 'video',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-05-11T10:00:00',
  },
  {
    id: 7,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Declaracion_Testigo.mp3',
    tipoDocumento: 'Medios Audiovisuales',
    tipoDocumentoId: 21,
    tamanio: 3145728,
    mimeType: 'audio/mpeg',
    extension: 'mp3',
    categoria: 'audio',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-05-11T11:30:00',
  },
  {
    id: 8,
    expedienteId: 1,
    expedienteNumero: '01173-2026-00045',
    nombreOriginal: 'Borrador_Contrato.docx',
    tipoDocumento: 'Otros Documentos',
    tipoDocumentoId: 23,
    tamanio: 102400,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    extension: 'docx',
    categoria: 'word',
    usuarioCreacion: 'abogado.qa',
    fechaCreacion: '2026-05-12T09:15:00',
  },
];

export const DTO_DOCUMENTO_VIEWER: Documento = DTO_DOCUMENTOS_EXP1[0];
