import { ExpedienteResponse } from '../models/expediente.model';

export const DTO_EXPEDIENTES: ExpedienteResponse[] = [
  {
    id: 1,
    numero: '01173-2026-00045',
    tipoProcesoId: 1,
    juzgadoId: 1,
    estadoId: 1,
    fechaInicio: '2026-04-19',
    descripcion: 'Juicio Ordinario de Daños y Perjuicios',
    actorPrincipal: 'María García López',
    demandado: 'Construcciones Rápidas S.A.',
    usuarioCreacion: 'admin.qa',
    fechaCreacion: '2026-04-19T08:30:00',
    totalDocumentos: 5,
  },
  {
    id: 2,
    numero: '01108-2026-01234',
    tipoProcesoId: 2,
    juzgadoId: 1,
    estadoId: 1,
    fechaInicio: '2026-04-10',
    descripcion: 'Proceso Penal por Estafa Propia',
    actorPrincipal: 'Ministerio Público',
    demandado: 'Carlos Rodríguez Estrada',
    usuarioCreacion: 'admin.qa',
    fechaCreacion: '2026-04-10T10:15:00',
    totalDocumentos: 6,
  },
  {
    id: 3,
    numero: '01024-2026-00088',
    tipoProcesoId: 3,
    juzgadoId: 1,
    estadoId: 1,
    fechaInicio: '2026-04-05',
    descripcion: 'Juicio Ordinario Laboral por Despido Injustificado',
    actorPrincipal: 'Ana Lucía Pérez Morales',
    demandado: 'Empresa Textil Guatemala S.A.',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-04-05T09:00:00',
    totalDocumentos: 3,
  },
  {
    id: 4,
    numero: '01044-2026-00321',
    tipoProcesoId: 4,
    juzgadoId: 1,
    estadoId: 1,
    fechaInicio: '2026-04-12',
    descripcion: 'Pensión Alimenticia Provisional',
    actorPrincipal: 'Sofía Mendoza de López',
    demandado: 'Roberto López Juárez',
    usuarioCreacion: 'secretario.qa',
    fechaCreacion: '2026-04-12T11:00:00',
    totalDocumentos: 3,
  },
  {
    id: 5,
    numero: '01069-2026-00012',
    tipoProcesoId: 7,
    juzgadoId: 1,
    estadoId: 3,
    fechaInicio: '2026-04-08',
    descripcion: 'Femicidio en grado de tentativa — Decreto 22-2008',
    actorPrincipal: 'Ministerio Público',
    demandado: 'Jorge Vásquez Ramírez',
    usuarioCreacion: 'admin.qa',
    fechaCreacion: '2026-04-08T07:45:00',
    totalDocumentos: 3,
  },
  {
    id: 6,
    numero: '01075-2025-00992',
    tipoProcesoId: 5,
    juzgadoId: 1,
    estadoId: 2,
    fechaInicio: '2025-11-20',
    descripcion: 'Ejecución Mercantil por Cobro de Pagaré',
    actorPrincipal: 'Banco de Guatemala',
    demandado: 'Importaciones del Sur S.A.',
    usuarioCreacion: 'admin.qa',
    fechaCreacion: '2025-11-20T14:30:00',
    totalDocumentos: 2,
  },
];

export const DTO_EXPEDIENTE_DETALLE: ExpedienteResponse = DTO_EXPEDIENTES[0];
